trigger:
  branches:
    include:
      - main   # pipeline triggers on pushes to main branch

pool:
  name: SelfHostedPool   # your Linux VM agent pool

steps:
- script: ./run.sh   # only runs your run.sh script

