trigger:
  branches:
    include:
      - main   # runs pipeline on any push to main branch

pool:
  name: SelfHostedPool

steps:
- script: echo "Hello, DevOps from Azure Pipeline!"
  displayName: 'Print Hello World'

- script: |
    chmod +x run.sh
    ./run.sh
  displayName: 'Run hello script'
